trigger:
  - master

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: azure-pybuild.yml
  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: azure-pybuild.yml
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-pybuild.yml
  - job: Check
    dependsOn:
      - Windows
      - macOS
      - Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          pip install -r test-requirements.txt
          python setup.py release --azure
        name: release
  - job: pypitest
    condition: eq( dependencies.Check.outputs['release.type'], 'minor')
    dependsOn: Check
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          python setup.py sdist bdist_wheel
        name: dist
      - task: TwineAuthenticate@0
        inputs:
          externalFeeds: pypitest
      - script: twine upload -r pypitest --config-file $PYPIRC_PATH dist/*
        name: twine
  - job: pypi
    condition: eq( dependencies.Check.outputs['release.type'], 'major')
    dependsOn: Check
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      release_type: $[ dependencies.Check.outputs['release.type'] ]
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          python setup.py sdist bdist_wheel
        name: dist
      - task: TwineAuthenticate@0
        inputs:
          externalFeeds: pypi
      - script: twine upload -r pypi --config-file $PYPIRC_PATH dist/*
        name: twine
